
# Data module configs
data:
  batch_size: 16
  val_dataset: 'sst2' # options ['sst2', 'tweet']
  trn_dataset: 'sst2' # options ['sst2', 'tweet', 'sst2-tweet']
  tokenizer: google/bert_uncased_L-2_H-128_A-2

# Distillation configs

distillation:
  epochs: 5
  learning_rate: 3e-5


# Weight-and-bias config
wandb:
  project: kd_final
  exp: textbrewer-bert_H192_L4_A12-epoch=07-sst2

# Teacher
teacher_model:  ckpts/bert-base-uncased-epoch=02-val_loss=0.22

# Student
student_model: ckpts/bert_H192_L4_A12-epoch=07-perplexity=17.83

ckpt_path: ckpts/


