
# Data module configs
data:
  batch_size: 32
  max_length: 128

# Distillation configs

distillation:
  epochs: 10
  learning_rate: 3e-5
  adaptors:
    - 'AttnMiniLM'
    - 'ValMiniLM'
    - 'LogitMSE'

# Weight-and-bias config
wandb:
  project: knowledge-distillation-multilingual
  exp: test


