
# Data module configs
data:
  batch_size: 32
  val_dataset: 'sst2' # options ['sst2', 'tweet']
  trn_dataset: 'sst2' # options ['sst2', 'tweet', 'sst2-tweet']
  tokenizer: google/bert_uncased_L-2_H-128_A-2
  train_with_label: 1

# Distillation configs

distillation:
  epochs: 3
  learning_rate: 3e-5
  loss_list_ptr:
    - 'embd:mse'
    - 'hidn:mse'
  loss_list_ft:
    - 'pred:nll'
    - 'pred:mse'
    - 'hidn:mse'

# Weight-and-bias config
wandb:
  project: knowledge-distillation-sst2
  exp: test

# Teacher
teacher_model:  ckpts/bert-base-uncased-epoch=02-val_loss=0.22

# Student
student_model: configs/bert_uncased/bert_tiny_uncased.yaml

