
# Data module configs
data:
  batch_size: 32
  max_length: 128
  num_workers: 0

# Training configs
training:
  epochs: 20
  learning_rate: 3e-5
  weight_decay: 5e-5
  eps: 1e-8

# Weight-and-bias config
wandb:
  project: multilingual_finetune
  exp: xlm_roberta_base_amazon

# Setting save path for the fine-tuned student
ckpt_path: ckpts/


