
# Data module configs
data:
  batch_size: 32
  max_length: 128
  tokenizer: google/bert_uncased_L-2_H-128_A-2
  dataset_name: 'sst2' # options ['sst2', 'tweet']

# Distillation configs
training:
  epochs: 6
  learning_rate: 3e-5

# Weight-and-bias config
wandb:
  project: finetune
  exp: bert_uncased_L-2_H-128_A-2-sst2

# Setting pre-trained model
model: google/bert_uncased_L-2_H-128_A-2
ckpt_path: ckpts/


