
# Data module configs
data:
  batch_size: 32
  max_length: 128
  tokenizer: google/bert_uncased_L-2_H-128_A-2
  dataset_name: 'sst2' # options ['sst2', 'tweet']

# Distillation configs
training:
  epochs: 10
  learning_rate: 3e-5

# Weight-and-bias config
wandb:
  project: finetune
  exp: bert-base-uncased-tiny-A12-sst2

# Setting pre-trained model
model: ckpts/bert-base-uncased-tiny-a12
ckpt_path: ckpts/


